export const cardData = [
  {
    link: '/en/learn/module-0',
    title: 'Introduction to Kernel',
    emoji: '🌠',
    personalInquiry: '🌈 Play of Pattern',
    personalInquiryLink: '/en/learn/module-0/play-of-pattern',
    webInquiry: '✍️ Trust',
    webInquiryLink: '/en/learn/module-0/trust',
    backLinks: [
      { link: '/en/learn/module-0/money-language', title: 'Money Talks' },
      { link: '/en/learn/module-0/weird-ways', title: 'In Weird Ways' },
      { link: '/en/learn/module-0/conversation', title: 'Try Listening' },
      { link: '/en/learn/module-0/purpose', title: 'With Love' },
    ],
  },
  {
    link: '/en/learn/module-1',
    title: "Ethereum's History and State",
    emoji: '🌍',
    personalInquiry: '🤯 Meaning',
    personalInquiryLink: '/en/learn/module-1/meaning',
    webInquiry: '💯 Value',
    webInquiryLink: '/en/learn/module-1/value',
    backLinks: [
      { link: '/en/learn/module-1/playdough-protocols', title: 'Shaping' },
      {
        link: '/en/learn/module-1/understanding-ethereum',
        title: "Ethereum's",
      },
      { link: '/en/learn/module-1/dreamers', title: 'Dreamers Of' },
      {
        link: '/en/learn/module-1/joyful-subversion',
        title: 'Joyful Subversion',
      },
    ],
  },
  {
    link: '/en/learn/module-2',
    title: 'A Global Financial System',
    emoji: '💰',
    personalInquiry: '⁉️ Better Questions',
    personalInquiryLink: '/en/learn/module-2/better-questions',
    webInquiry: '💸 Money and Speech',
    webInquiryLink: '/en/learn/module-2/money-speech',
    backLinks: [
      { link: '/en/learn/module-2/shelling-out', title: 'Collecting' },
      { link: '/en/learn/module-2/debt', title: 'Debt' },
      { link: '/en/learn/module-2/banking', title: 'In Pyramids?' },
      {
        link: '/en/learn/module-2/engineering',
        title: 'Engineer Better Solutions!',
      },
    ],
  },
  {
    link: '/en/learn/module-3',
    title: 'Take Back The Web',
    emoji: '🌐',
    personalInquiry: '🔍 Intention',
    personalInquiryLink: '/en/learn/module-3/intention',
    webInquiry: '🦄 Freedom',
    webInquiryLink: '/en/learn/module-3/freedom',
    backLinks: [
      { link: '/en/learn/module-3/remember', title: 'Remember' },
      { link: '/en/learn/module-3/time', title: 'The Present Time.' },
      { link: '/en/learn/module-3/lock-it-open', title: 'Lock It Open' },
      { link: '/en/learn/module-3/humility', title: 'With Humility' },
    ],
  },
  {
    link: '/en/learn/module-4',
    title: 'Internet Age Institutions',
    emoji: 'ℹ️',
    personalInquiry: '👑 Govern Yourself',
    personalInquiryLink: '/en/learn/module-4/governance',
    webInquiry: '➕ Radically',
    webInquiryLink: '/en/learn/module-4/liberal-radical',
    backLinks: [
      { link: '/en/learn/module-4/art', title: 'Transform' },
      { link: '/en/learn/module-4/consensus', title: 'Consensus' },
      { link: '/en/learn/module-4/self-enquiry', title: 'By Inventing' },
      { link: '/en/learn/module-4/the-garden', title: 'Paradise' },
    ],
  },
  {
    link: '/en/learn/module-5',
    title: 'Tokens and Mechanism Design',
    emoji: '📈',
    personalInquiry: '👂 Listening and Stories',
    personalInquiryLink: '/en/learn/module-5/listening-stories',
    webInquiry: '👨‍👩‍👧‍👦 Incentives',
    webInquiryLink: '/en/learn/module-5/incentives',
    backLinks: [
      {
        link: '/en/learn/module-5/amazon-unbounded-search',
        title: 'Unbounded Search',
      },
      {
        link: '/en/learn/module-5/the-peoples-narrative',
        title: 'Through Narrative',
      },
      {
        link: '/en/learn/module-5/reveal-the-universe',
        title: 'Reveals Universes',
      },
      {
        link: '/en/learn/module-5/prosocial-value',
        title: 'Of Prosocial Value',
      },
    ],
  },
  {
    link: '/en/learn/module-6',
    title: 'Scaling Principled Games',
    emoji: '⚖️',
    personalInquiry: '🎓 Learn How To Learn',
    personalInquiryLink: '/en/learn/module-6/en/learn',
    webInquiry: '👮 Censorship Resistance',
    webInquiryLink: '/en/learn/module-6/censorship-resistance',
    backLinks: [
      { link: '/en/learn/module-6/serenity', title: 'Serenely' },
      { link: '/en/learn/module-6/particpate', title: 'Participate In' },
      {
        link: '/en/learn/module-6/inventing-on-principle',
        title: 'Principled',
      },
      { link: '/en/learn/module-6/duende', title: 'Deep Song' },
    ],
  },
  {
    link: '/en/learn/module-7',
    title: 'The Gift',
    emoji: '🎁',
    personalInquiry: '💝 Giving',
    personalInquiryLink: '/en/learn/module-7/giving',
    webInquiry: '🏊 Scale-ability',
    webInquiryLink: '/en/learn/module-7/scale-ability',
    backLinks: [
      { link: '/en/learn/module-7/the-gift', title: 'The Gift' },
      { link: '/en/learn/module-7/no-paradigm', title: 'Of No Paradigm' },
      { link: '/en/learn/module-7/perfection', title: 'Is Perfection' },
    ],
  },
  {
    link: '/en/learn/module-metta',
    title: 'Mettā',
    emoji: '🤯',
    personalInquiry: '🎓 School Sucks',
    personalInquiryLink: '/en/learn/module-metta/school-sucks',
    webInquiry: '🕯️ Build Native Altars',
    webInquiryLink: '/en/learn/module-metta/build-native-altars',
    backLinks: [
      { link: '/en/learn/module-metta/start-small', title: 'Start Small' },
      {
        link: '/en/learn/module-metta/beautiful-homes',
        title: 'Beautiful Homes',
      },
      { link: '/en/learn/module-metta/realise-love', title: 'Realise Love' },
    ],
  },
]
